CREATE TABLE IF NOT EXISTS public.participants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  email TEXT,
  access_code TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.draws (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  drawer TEXT NOT NULL UNIQUE,
  drawn TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS draws_drawer_idx ON public.draws (drawer);
CREATE INDEX IF NOT EXISTS draws_drawn_idx ON public.draws (drawn);

ALTER TABLE public.draws ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users"
ON public.draws
FOR SELECT
USING (true);

CREATE POLICY "Enable insert access for all users"
ON public.draws
FOR INSERT
WITH CHECK (true);

CREATE POLICY "Enable delete access for all users"
ON public.draws
FOR DELETE
USING (true);

ALTER TABLE public.participants ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users"
ON public.participants
FOR SELECT
USING (true);

INSERT INTO participants (name, email, access_code)
SELECT
  name,
  email,
  UPPER(REPLACE(name, ' ', '')) || FLOOR(RANDOM() * 4001 + 1000)::TEXT
FROM (VALUES
  ('Aristide', 'aristide@example.com'),
  ('Hermann', 'hermann@example.com'),
  ('Cinthya', 'cinthya@example.com'),
  ('Mireille', 'mireille@example.com'),
  ('Clara', 'clara@example.com'),
  ('Tonton Clovis', 'clovis@example.com'),
  ('Paulin', 'paulin@example.com'),
  ('Esdras', 'esdras@example.com')
) AS participants(name, email);

